# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='file',
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
