# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20171116_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(path=b'/Users/kathrinschmitz/PycharmProjects/KS_Stream_3_LifestyleFitnessCoaching/media'),
        ),
    ]
